name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjhlMjcyYzItMmI1My00MTAzLTg2NjUtOGYyYzg5YzVjMDkyIiwidGVuYW50X2lkIjoiY2I4MjM4OTIyMzhiMzFlMTVlZmUzNjlkZDg3YWJiMjU1ZmYzNDE4OTQ0YjZkY2MwZmU1ZmMxMmMwOWNkNzc3NiIsImludGVybmFsX3NlY3JldCI6IjFhYTcyZWUxLTIzNTEtNGYxMi05ZjUwLWUzNjNlODIxNTUwMiJ9.4jXWYFVgUtcJk8olVvjtkhZ0SAyl49IWJxN5FjA2_nA"